// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type FlightRecord struct {
	FlightCode   string `json:"flightCode"`
	FlightStatus string `json:"flightStatus"`
	TimeStamp    string `json:"timeStamp"`
	Longitude    int64  `json:"longitude"`
	Latitude     int64  `json:"latitude"`
	Altitude     int    `json:"altitude"`
	SOC          int    `json:"SOC"`
}

type FlightRecordReq struct {
	FlightCode string `json:"flightCode"`
	StartTime  string `json:"startTime"`
	EndTime    string `json:"endTime"`
}

type FlightRecordResponse struct {
	Records []FlightRecord
}

type UasStatsResp struct {
	Total  int `json:"total"`
	Online int `json:"online"`
}
