// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type DroneStats struct {
	FlightCode   string `json:"flightCode"`
	FlightStatus string `json:"flightStatus"`
	TimeStamp    string `json:"timeStamp"`
	Longitude    int64  `json:"longitude"`
	Latitude     int64  `json:"latitude"`
	Altitude     int    `json:"altitude"`
	SOC          int    `json:"SOC"`
}

type DroneStatsResponse struct {
	Records []DroneStats
}

type FlightRecord struct {
	ID          int     `json:"id"`
	UavId       string  `json:"uav_id"`
	StartTime   string  `json:"start_time"`
	EndTime     string  `json:"end_time"`
	StartLat    int64   `json:"start_lat"`
	StartLng    int64   `json:"start_lng"`
	EndLat      int64   `json:"end_lat"`
	EndLng      int64   `json:"end_lng"`
	Distance    float64 `json:"distance"`
	BatteryUsed int     `json:"battery_used"`
	CreatedAt   string  `json:"created_at"`
}

type FlightRecordReq struct {
	FlightCode string `json:"flightCode"`
	StartTime  string `json:"startTime"`
	EndTime    string `json:"endTime"`
}

type FlightRecordsResponse struct {
	Flightrecords []FlightRecord `json:"flightRecords"`
}

type UasStatsResp struct {
	Total  int `json:"total"`
	Online int `json:"online"`
}
