// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"autonomous-vehicle/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/vehicle/current_mission",
				Handler: HandleGetCurrentMissionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vehicle/info",
				Handler: HandleGetVehicleInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vehicle/info_list",
				Handler: HandleGetVehicleInfoListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vehicle/list",
				Handler: HandleGetVehicleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vehicle/mileage_and_duration",
				Handler: HandleGetMileageAndDurationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vehicle/mission_by_subid",
				Handler: HandleGetMissionBySubIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vehicle/online_count",
				Handler: HandleOnlineCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vehicle/planning_route",
				Handler: HandleGetPlanningRouteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vehicle/station",
				Handler: HandleGetVehicleStationHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/vehicle/ws",
				Handler: HandleWebSocketHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/vehicle/export",
				Handler: ExportVehicleRecordsHandler(serverCtx),
			},
		},
	)
}
