// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"drone-stats-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/record/SOCUsage",
				Handler: SOCUsageStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/record/avgStats",
				Handler: AvgStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/record/export",
				Handler: ExportFlightRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/record/get",
				Handler: GetFlightRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/record/payloadStats",
				Handler: PayloadStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/record/query",
				Handler: QueryFlightRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/record/recentTracks",
				Handler: RecentTracksHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/record/stats",
				Handler: RecordsStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/record/timeSeries",
				Handler: TimeSeriesStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/record/uas",
				Handler: GetUasStatsHandler(serverCtx),
			},
		},
	)
}
