// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"drone-stats-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/flight/export",
				Handler: ExportFlightRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/flight/query",
				Handler: QueryFlightRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/flight/records",
				Handler: GetFlightRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/flight/stats",
				Handler: RecordsStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/uas/stats",
				Handler: GetUasStatsHandler(serverCtx),
			},
		},
	)
}
