// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type DroneStatusReq struct {
	RecordId   string  `json:"recordId"`
	UavType    string  `json:"uavType"`
	UavId      string  `json:"uavId"`
	TimeStamp  string  `json:"timeStamp"`
	FlightTime int     `json:"flightTime"`
	Longitude  int     `json:"longitude"`
	Latitude   int     `json:"latitude"`
	Altitude   float64 `json:"altitude"`
	Height     float64 `json:"height"`
	Course     float64 `json:"course"`
	Payload    int     `json:"payload"`
	Battery    int     `json:"battery"`
}

type DroneStatusResp struct {
	Code int `json:"code"`
}

type FlightRecordListResp struct {
	Total        int          `json:"total"`
	Records      []RecordItem `json:"records"`
	TotalUav     int          `json:"totalUav"`
	TotalFlights int          `json:"totalFlights"`
}

type FlightRecordReq struct {
	UavId       string `json:"uavId"`
	StartTime   string `json:"startTime"` // ISO8601格式
	EndTime     string `json:"endTime"`   // ISO8601格式
	StartLat    int    `json:"startLat"`
	StartLng    int    `json:"startLng"`
	EndLat      int    `json:"endLat"`
	EndLng      int    `json:"endLng"`
	Distance    int    `json:"distance"`
	BatteryUsed int    `json:"batteryUsed"`
}

type FlightRecordResp struct {
	Code int `json:"code"`
}

type FlightStatsResp struct {
	TotalFlights  int     `json:"totalFlights"`
	TotalDistance float64 `json:"totalDistance"`
}

type RecordItem struct {
	StartTime   int64   `json:"startTime"`
	EndTime     int64   `json:"endTime"`
	UavId       string  `json:"uavId"`
	Distance    float64 `json:"distance"`
	BatteryUsed int     `json:"batteryUsed"`
}
