// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type DroneStatusReq struct {
	OrderID        string `json:"orderID"`
	FlightCode     string `json:"flightCode"`
	Sn             string `json:"sn"`
	FlightStatus   string `json:"flightStatus"`
	ManufacturerID string `json:"manufacturerID"`
	UasID          string `json:"uasID"`
	TimeStamp      string `json:"timeStamp"`
	UasModel       string `json:"uasModel"`
	Coordinate     int    `json:"coordinate"`
	Longitude      int64  `json:"longitude"`
	Latitude       int64  `json:"latitude"`
	HeightType     int    `json:"heightType"`
	Height         int    `json:"height"`
	Altitude       int    `json:"altitude"`
	VS             int    `json:"VS"`
	GS             int    `json:"GS"`
	Course         int    `json:"course"`
	SOC            int    `json:"SOC"`
	RM             int    `json:"RM"`
	Voltage        int    `json:"voltage,optional"`
	Current        int    `json:"current,optional"`
	WindSpeed      int    `json:"windSpeed,optional"`
	WindDirect     int    `json:"windDirect,optional"`
	Temperture     int    `json:"temperture,optional"`
	Humidity       int    `json:"humidity,optional"`
}

type DroneStatusResp struct {
	Code     string `json:"code"`
	ErrorMsg bool   `json:"errorMsg"`
}

type FlightRecordReq struct {
	UasId       string `json:"uasId"`
	StartTime   string `json:"startTime"` // ISO8601格式
	EndTime     string `json:"endTime"`   // ISO8601格式
	StartLat    int64  `json:"startLat"`
	StartLng    int64  `json:"startLng"`
	EndLat      int64  `json:"endLat"`
	EndLng      int64  `json:"endLng"`
	Distance    int64  `json:"distance"`
	BatteryUsed int    `json:"batteryUsed"`
}

type FlightRecordResp struct {
	Code int `json:"code"`
}

type FlightStatsResp struct {
	TotalFlights  int     `json:"totalFlights"`
	TotalDistance float64 `json:"totalDistance"`
}

type OnlineCountResp struct {
	Count int `json:"count"`
}
