// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type DroneStatusReq struct {
	RecordId   string  `json:"recordId"`
	UavType    string  `json:"uavType"`
	UavId      string  `json:"uavId"`
	TimeStamp  string  `json:"timeStamp"`
	FlightTime int     `json:"flightTime"`
	Longitude  int     `json:"longitude"`
	Latitude   int     `json:"latitude"`
	Altitude   float64 `json:"altitude"`
	Height     float64 `json:"height"`
	Course     float64 `json:"course"`
}

type DroneStatusResp struct {
	Code int `json:"code"`
}
